version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: lobo-db
    restart: always
    environment:
      POSTGRES_USER: lobo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lobodb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: lobo-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}  

volumes:
  db_data:
